name: ai-cover
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ffmpeg
  - pip:
      - -e ./sample/python-audio-separator[cpu]
      - PySide6==6.8.1
      - fastapi==0.116.1
      - uvicorn[standard]==0.35.0
      - numpy
      - ffmpeg-normalize
      - Pillow
      - praat-parselmouth
      - rmvpe-onnx
      - scipy
      - soundfile==0.13.1
