name: ai-cover
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ffmpeg
  - pip:
      - -e ./sample/python-audio-separator[cpu]
      - PySide6==6.8.1
      - numpy
      - Pillow
      - praat-parselmouth
      - scipy
      - soundfile==0.13.1
